project:
  type: website

website:
  title: "Andrew Seaman – VS Code & Dev Environment Wiki"
  favicon: Images/favicon/favicon_VS-Code-logo.png
  back-to-top-navigation: true
  site-url: https://Andrew-J-Seaman.github.io/vs-code-dev-environment-wiki
  repo-url: https://github.com/Andrew-J-Seaman/vs-code-dev-environment-wiki
  issue-url: https://github.com/Andrew-J-Seaman/vs-code-dev-environment-wiki/issues/new
  repo-actions: [issue]

  page-footer: 
    border: true
    left: "Andrew Seaman 2025©"
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/andrew-james-seaman/

  navbar:
    background: primary
    search: true
    right:
      - text: "Home"
        file: index.qmd
      - text: "Theme Tracker"
        file: Notes/meta-themes.qmd
      - text: "UML Design Tools"
        file: Notes/uml-tools.qmd

  sidebar:
    - title: "Dev Environment Notes"
      style: "docked"
      background: light
      contents:
        - Notes/meta-themes.qmd
        - Notes/uml-tools.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc_float:
      collapsed: false
      position: left

publish:
  provider: gh-pages
    

